### ISSUE TITLE
Android 10-11 MeeGo Adaptive Icon-Shape Magisk Module Support

### ISSUE THREAD

**Issue by Ali382829** [yeyebbc/MeeGo-Adaptive-Icon-Shape-Magisk-Module#1]
MeeGo Adaptive Icon-Shape Magisk Module May Not Work On Android 10-11 Support
Only Support Android 12-13 Support
This MeeGo Adaptive Icon-Shape Is Min 29 (Android 10)
Not Possible To Install MeeGo Adaptive Icon-Shape Magisk Module On Android 10-11
Not Support Android 10-11 MeeGo Adaptive Icon-Shape Magisk Module Due Broken Support
Vphonegaga Gold 64bit Running Android 10 Can Not Install MeeGo Adaptive Icon-Shape Magisk Module
Infnix Smart 5 Pro Or Infinix Hot 10i Running Android 11 Can Not Install MeeGo Adaptive Icon-Shape Magisk Module
Only Work For Android 12-13 To Install MeeGo Adaptive Icon-Shape Magisk Module

Images

![Screenshot_20241030-202859~2](https://github.com/user-attachments/assets/e13ea8e0-22b5-4045-bff9-dcfefdc38df5)

Fix

Install Android 12 Or 13 Custom ROM Using Custom Recovery
Install Magisk Using Custom Recovery
Install MeeGo Adaptive Icon-Shape Magisk Module

Notes

The Issues Is Closed Is Not Planned

**Comment by Ali382829** [comment]
Closed As Not Planned Yes

**Comment by yeyebbc** [comment]
Oh so you are not a bot.

**Comment by Ali382829** [comment]
Is Not Bot

**Comment by yeyebbc** [comment]
Go read README.md

**Comment by Ali382829** [comment]
README.md Screenshots

![Screenshot_20241201_165757_Chrome](https://github.com/user-attachments/assets/076d4ce1-db0d-480f-9031-e33dcc8f6c07)

**Comment by yeyebbc** [comment]
Requirements:
- Android 12 (maybe)

**Comment by Ali382829** [comment]
Android 10/11 Installing MeeGo Adaptive Icon-Shape Magisk Module Failed

**Comment by Ali382829** [comment]
1. Android 10 MeeGo Adaptive Icon-Shape Magisk Module Not Work

2. Android 11 MeeGo Adaptive Icon-Shape Magisk Module Not Work

3. Android 12+ MeeGo Adaptive Icon-Shape Magisk Module Work (Android 14/15 MeeGo Adaptive Icon-Shape Magisk Module Not Tested)
